[tool.isort]
profile = "black"
multi_line_output = 3
lines_after_imports = 2
order_by_type = true
force_sort_within_sections = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["devfriend"]
